### ISSUE TITLE
Cant get the settings.yml file into the deployment

### ISSUE THREAD

**Issue by Murf** [tiagoposse/psono-helm-chart#2]
Hi, I added the settings file (I just copied examples/environment.yml) into the values.yml file thusly:
server:
  enabled: true
  replicas: 1
...
  envFiles: [settings.yml]

I deploy to OKD (Openshift) and it deploys ok, as I can see in the server deployment the start command is:
command:
            - sh
            - '-c'
            - >
              export $(xargs < settings.yml);
              /root/configs/docker/cmd.sh

Only issue is the deployment cant find the settings.yml file, how do I include it into the helm deployment that is installed to the cluster?

Container log:
sh: can't open settings.yml: no such file

Thanks in advance

**Comment by chickahoona** [comment]
There is no need to get a settings.yaml into the deployment. All paramaters that you can specify within the settings.yaml can be provided as "environment variables" to the system. There are a couple of examples how to do that here:
https://github.com/tiagoposse/psono-helm-chart/tree/main/examples

The part in the psono docu that explains that can be found here:
https://doc.psono.com/admin/other/environment-variables.html

**Comment by tiagoposse** [comment]
I'm late to the party.
Here's an example for the current chart. Might need some minor changes :)

```
envFiles:
  - settings.yaml
 
server:
  extraVolumeMounts:
    - name: config-volume
      mountPath: /root/settings.yaml
      subPath: settings.yaml
  extraVolums:
    - name: config-volume
      configMap:
        name: my-config
```
